name: simey test
favicon: null
layout_spectrum: 0.3626600047573447
typography_spectrum: 0.8537291111424565
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f7'
    - '#d0cfca'
    - '#505962'
    - '#979596'
    - '#7e7e7e'
  brandStrength: 0.125
  lightness: 0.1875
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
