name: simey test
favicon: null
layout_spectrum: 0.3626600047573447
typography_spectrum: 0.8537291111424565
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.016837605042383075
  lightness: 0.7807544153183699
  saturation: 0.5847550623584539
  rhythmicContrast: 0.30537295690737665
purpose: []
